steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west3-docker.pkg.dev/bdobdo/portfolio-repo/frontend:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west3-docker.pkg.dev/bdobdo/portfolio-repo/frontend:latest']
images:
- 'europe-west3-docker.pkg.dev/bdobdo/portfolio-repo/frontend:latest'
